# Generated by Django 3.1.2 on 2020-10-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegioniItaliane',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField()),
                ('codice_regione', models.IntegerField()),
                ('denominazione_regione', models.CharField(max_length=30)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('ricoverati_con_sintomi', models.IntegerField()),
                ('terapia_intensiva', models.IntegerField()),
                ('totale_ospedalizzati', models.IntegerField()),
                ('isolamento_domiciliare', models.IntegerField()),
                ('totale_positivi', models.IntegerField()),
                ('variazione_totale_positivi', models.IntegerField()),
                ('nuovi_positivi', models.IntegerField()),
                ('dimessi_guariti', models.IntegerField()),
                ('deceduti', models.IntegerField()),
                ('casi_da_sospetto_diagnostico', models.IntegerField()),
                ('casi_da_screening', models.IntegerField()),
                ('totale_casi', models.IntegerField()),
                ('tamponi', models.IntegerField()),
                ('casi_testati', models.IntegerField()),
                ('popolazione', models.IntegerField()),
                ('incidenza', models.IntegerField()),
                ('variazione_casi_da_screening', models.IntegerField()),
                ('variazione_casi_da_sospetto_diagnostico', models.IntegerField()),
                ('variazione_casi_testati', models.IntegerField()),
                ('variazione_deceduti', models.IntegerField()),
                ('variazione_dimessi_guariti', models.IntegerField()),
                ('variazione_isolamento_domiciliare', models.IntegerField()),
                ('variazione_ricoverati_con_sintomi', models.IntegerField()),
                ('variazione_tamponi', models.IntegerField()),
                ('variazione_terapia_intensiva', models.IntegerField()),
                ('percentuale_variazione_casi_da_screening', models.FloatField()),
                ('percentuale_variazione_casi_da_sospetto_diagnostico', models.FloatField()),
                ('percentuale_variazione_casi_testati', models.FloatField()),
                ('percentuale_variazione_deceduti', models.FloatField()),
                ('percentuale_variazione_dimessi_guariti', models.FloatField()),
                ('percentuale_variazione_isolamento_domiciliare', models.FloatField()),
                ('percentuale_variazione_ricoverati_con_sintomi', models.FloatField()),
                ('percentuale_variazione_tamponi', models.FloatField()),
                ('percentuale_variazione_terapia_intensiva', models.FloatField()),
                ('variazione_casi_da_screening_3dma', models.IntegerField()),
                ('variazione_casi_da_sospetto_diagnostico_3dma', models.IntegerField()),
                ('variazione_casi_testati_3dma', models.IntegerField()),
                ('variazione_deceduti_3dma', models.IntegerField()),
                ('variazione_dimessi_guariti_3dma', models.IntegerField()),
                ('variazione_isolamento_domiciliare_3dma', models.IntegerField()),
                ('variazione_ricoverati_con_sintomi_3dma', models.IntegerField()),
                ('variazione_tamponi_3dma', models.IntegerField()),
                ('variazione_terapia_intensiva_3dma', models.IntegerField()),
                ('variazione_casi_da_screening_7dma', models.IntegerField()),
                ('variazione_casi_da_sospetto_diagnostico_7dma', models.IntegerField()),
                ('variazione_casi_testati_7dma', models.IntegerField()),
                ('variazione_deceduti_7dma', models.IntegerField()),
                ('variazione_dimessi_guariti_7dma', models.IntegerField()),
                ('variazione_isolamento_domiciliare_7dma', models.IntegerField()),
                ('variazione_ricoverati_con_sintomi_7dma', models.IntegerField()),
                ('variazione_tamponi_7dma', models.IntegerField()),
                ('variazione_terapia_intensiva_7dma', models.IntegerField()),
                ('incidenza_7d', models.IntegerField()),
                ('nuovi_positivi_7dma', models.IntegerField()),
                ('nuovi_positivi_3dma', models.IntegerField()),
                ('percentuale_positivi_tamponi', models.FloatField()),
                ('percentuale_positivi_tamponi_giornaliera', models.FloatField()),
                ('percentuale_positivi_casi', models.FloatField()),
                ('percentuale_positivi_casi_giornaliera', models.FloatField()),
                ('cfr', models.FloatField()),
            ],
            options={
                'verbose_name': 'Riepilogo Italia',
                'verbose_name_plural': 'Riepilogo Italia',
            },
        ),
    ]
