# Generated by Django 3.1.2 on 2020-10-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regioni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regioniitaliane',
            name='incidenza',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='regioniitaliane',
            name='incidenza_7d',
            field=models.FloatField(),
        ),
    ]
