# Generated by Django 3.1.2 on 2020-11-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regioni', '0002_auto_20201029_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='regioniitaliane',
            name='percentuale_positivi_casi_3dma',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regioniitaliane',
            name='percentuale_positivi_casi_7dma',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
