# Generated by Django 3.1.2 on 2020-11-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regioni', '0003_auto_20201109_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='regioniitaliane',
            name='nuovi_positivi_7d_incr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regioniitaliane',
            name='nuovi_positivi_7dsum',
            field=models.IntegerField(default=0),
        ),
    ]
