# Generated by Django 3.1.2 on 2020-11-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regioni', '0004_auto_20201121_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='regioniitaliane',
            name='deceduti_7d_incr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regioniitaliane',
            name='deceduti_7dsum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regioniitaliane',
            name='dimessi_guariti_7d_incr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regioniitaliane',
            name='dimessi_guariti_7dsum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regioniitaliane',
            name='ricoverati_con_sintomi_7d_incr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regioniitaliane',
            name='ricoverati_con_sintomi_7dsum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regioniitaliane',
            name='terapia_intensiva_7d_incr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regioniitaliane',
            name='terapia_intensiva_7dsum',
            field=models.IntegerField(default=0),
        ),
    ]
