# Generated by Django 3.1.2 on 2020-12-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regioni', '0005_auto_20201121_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='regioniitaliane',
            name='ingressi_terapia_intensiva',
            field=models.IntegerField(default=0),
        ),
    ]
