# Generated by Django 3.1.2 on 2020-12-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regioni', '0006_regioniitaliane_ingressi_terapia_intensiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='regioniitaliane',
            name='percentuale_variazione_ingressi_terapia_intensiva',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='regioniitaliane',
            name='variazione_ingressi_terapia_intensiva',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regioniitaliane',
            name='variazione_ingressi_terapia_intensiva_3dma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regioniitaliane',
            name='variazione_ingressi_terapia_intensiva_7dma',
            field=models.IntegerField(default=0),
        ),
    ]
