# Generated by Django 3.1.2 on 2020-10-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceItaliane',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField()),
                ('codice_regione', models.IntegerField()),
                ('denominazione_regione', models.CharField(max_length=30)),
                ('codice_provincia', models.IntegerField()),
                ('denominazione_provincia', models.CharField(max_length=30)),
                ('siglae_provincia', models.CharField(max_length=10)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('totale_casi', models.IntegerField()),
                ('incidenza', models.IntegerField()),
                ('variazione_totale_casi', models.IntegerField()),
                ('percentuale_variazione_totale_casi', models.FloatField()),
                ('variazione_totale_casi_3dma', models.IntegerField()),
                ('variazione_totale_casi_7dma', models.IntegerField()),
                ('incidenza_7d', models.FloatField()),
            ],
            options={
                'verbose_name': 'Riepilogo Province',
                'verbose_name_plural': 'Riepilogo Province',
            },
        ),
    ]
