# Generated by Django 3.1.2 on 2020-10-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provinceitaliane',
            old_name='siglae_provincia',
            new_name='sigla_provincia',
        ),
    ]
