# Generated by Django 3.1.2 on 2020-10-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0002_auto_20201029_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provinceitaliane',
            name='incidenza',
            field=models.FloatField(),
        ),
    ]
