# Generated by Django 3.1.2 on 2020-11-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0003_auto_20201029_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='provinceitaliane',
            name='nuovi_positivi_7d_incr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provinceitaliane',
            name='nuovi_positivi_7dsum',
            field=models.IntegerField(default=0),
        ),
    ]
